//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 02:37:29 PM CEST 
//


package com.irdeto.jumpstart.domain.xmltv;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.irdeto.jumpstart.domain.xmltv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Commentator_QNAME = new QName("", "commentator");
    private final static QName _Director_QNAME = new QName("", "director");
    private final static QName _Adapter_QNAME = new QName("", "adapter");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _Presenter_QNAME = new QName("", "presenter");
    private final static QName _Colour_QNAME = new QName("", "colour");
    private final static QName _Present_QNAME = new QName("", "present");
    private final static QName _Composer_QNAME = new QName("", "composer");
    private final static QName _Editor_QNAME = new QName("", "editor");
    private final static QName _Aspect_QNAME = new QName("", "aspect");
    private final static QName _Stereo_QNAME = new QName("", "stereo");
    private final static QName _Quality_QNAME = new QName("", "quality");
    private final static QName _Producer_QNAME = new QName("", "producer");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Guest_QNAME = new QName("", "guest");
    private final static QName _Writer_QNAME = new QName("", "writer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.irdeto.jumpstart.domain.xmltv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Desc }
     * 
     */
    public Desc createDesc() {
        return new Desc();
    }

    /**
     * Create an instance of {@link EpisodeNum }
     * 
     */
    public EpisodeNum createEpisodeNum() {
        return new EpisodeNum();
    }

    /**
     * Create an instance of {@link Credits }
     * 
     */
    public Credits createCredits() {
        return new Credits();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link StarRating }
     * 
     */
    public StarRating createStarRating() {
        return new StarRating();
    }

    /**
     * Create an instance of {@link Icon }
     * 
     */
    public Icon createIcon() {
        return new Icon();
    }

    /**
     * Create an instance of {@link Length }
     * 
     */
    public Length createLength() {
        return new Length();
    }

    /**
     * Create an instance of {@link Premiere }
     * 
     */
    public Premiere createPremiere() {
        return new Premiere();
    }

    /**
     * Create an instance of {@link SubTitle }
     * 
     */
    public SubTitle createSubTitle() {
        return new SubTitle();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Subtitles }
     * 
     */
    public Subtitles createSubtitles() {
        return new Subtitles();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link DisplayName }
     * 
     */
    public DisplayName createDisplayName() {
        return new DisplayName();
    }

    /**
     * Create an instance of {@link Audio }
     * 
     */
    public Audio createAudio() {
        return new Audio();
    }

    /**
     * Create an instance of {@link LastChance }
     * 
     */
    public LastChance createLastChance() {
        return new LastChance();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Programme }
     * 
     */
    public Programme createProgramme() {
        return new Programme();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link OrigLanguage }
     * 
     */
    public OrigLanguage createOrigLanguage() {
        return new OrigLanguage();
    }

    /**
     * Create an instance of {@link PreviouslyShown }
     * 
     */
    public PreviouslyShown createPreviouslyShown() {
        return new PreviouslyShown();
    }

    /**
     * Create an instance of {@link New }
     * 
     */
    public New createNew() {
        return new New();
    }

    /**
     * Create an instance of {@link XmlTvRating }
     * 
     */
    public XmlTvRating createRating() {
        return new XmlTvRating();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Tv }
     * 
     */
    public Tv createTv() {
        return new Tv();
    }

    /**
     * Create an instance of {@link XmlTvChannel }
     * 
     */
    public XmlTvChannel createChannel() {
        return new XmlTvChannel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "commentator")
    public JAXBElement<String> createCommentator(String value) {
        return new JAXBElement<String>(_Commentator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "director")
    public JAXBElement<String> createDirector(String value) {
        return new JAXBElement<String>(_Director_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "adapter")
    public JAXBElement<String> createAdapter(String value) {
        return new JAXBElement<String>(_Adapter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "presenter")
    public JAXBElement<String> createPresenter(String value) {
        return new JAXBElement<String>(_Presenter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "colour")
    public JAXBElement<String> createColour(String value) {
        return new JAXBElement<String>(_Colour_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "present")
    public JAXBElement<String> createPresent(String value) {
        return new JAXBElement<String>(_Present_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "composer")
    public JAXBElement<String> createComposer(String value) {
        return new JAXBElement<String>(_Composer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "editor")
    public JAXBElement<String> createEditor(String value) {
        return new JAXBElement<String>(_Editor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aspect")
    public JAXBElement<String> createAspect(String value) {
        return new JAXBElement<String>(_Aspect_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stereo")
    public JAXBElement<String> createStereo(String value) {
        return new JAXBElement<String>(_Stereo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quality")
    public JAXBElement<String> createQuality(String value) {
        return new JAXBElement<String>(_Quality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "producer")
    public JAXBElement<String> createProducer(String value) {
        return new JAXBElement<String>(_Producer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "guest")
    public JAXBElement<String> createGuest(String value) {
        return new JAXBElement<String>(_Guest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "writer")
    public JAXBElement<String> createWriter(String value) {
        return new JAXBElement<String>(_Writer_QNAME, String.class, null, value);
    }

}
