//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 02:37:29 PM CEST 
//


package com.irdeto.jumpstart.domain.xmltv;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}channel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}programme" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.tv"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel",
    "programme"
})
@XmlRootElement(name = "tv")
public class Tv {

    protected List<XmlTvChannel> channel;
    protected List<Programme> programme;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "anySimpleType")
    protected String date;
    @XmlAttribute(name = "source-info-url")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceInfoUrl;
    @XmlAttribute(name = "source-info-name")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceInfoName;
    @XmlAttribute(name = "source-data-url")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceDataUrl;
    @XmlAttribute(name = "generator-info-name")
    @XmlSchemaType(name = "anySimpleType")
    protected String generatorInfoName;
    @XmlAttribute(name = "generator-info-url")
    @XmlSchemaType(name = "anySimpleType")
    protected String generatorInfoUrl;

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlTvChannel }
     * 
     * 
     */
    public List<XmlTvChannel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<XmlTvChannel>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the programme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the programme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgramme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Programme }
     * 
     * 
     */
    public List<Programme> getProgramme() {
        if (programme == null) {
            programme = new ArrayList<Programme>();
        }
        return this.programme;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the sourceInfoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceInfoUrl() {
        return sourceInfoUrl;
    }

    /**
     * Sets the value of the sourceInfoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceInfoUrl(String value) {
        this.sourceInfoUrl = value;
    }

    /**
     * Gets the value of the sourceInfoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceInfoName() {
        return sourceInfoName;
    }

    /**
     * Sets the value of the sourceInfoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceInfoName(String value) {
        this.sourceInfoName = value;
    }

    /**
     * Gets the value of the sourceDataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDataUrl() {
        return sourceDataUrl;
    }

    /**
     * Sets the value of the sourceDataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDataUrl(String value) {
        this.sourceDataUrl = value;
    }

    /**
     * Gets the value of the generatorInfoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorInfoName() {
        return generatorInfoName;
    }

    /**
     * Sets the value of the generatorInfoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorInfoName(String value) {
        this.generatorInfoName = value;
    }

    /**
     * Gets the value of the generatorInfoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorInfoUrl() {
        return generatorInfoUrl;
    }

    /**
     * Sets the value of the generatorInfoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorInfoUrl(String value) {
        this.generatorInfoUrl = value;
    }

}
