<?php
/**
 * @package    Irdeto\Entity
 * @subpackage Tests
 * @copyright  Copyright (c) 2009-2013 Irdeto (http://www.irdeto.com)
 */

namespace Irdeto\Entity\Recipe\Jumpstart;

use Irdeto\Entity\Recipe\AbstractRecipeSeed;

/**
 * @package    Irdeto\Entity
 * @subpackage Tests
 * @copyright  Copyright (c) 2009-2013 Irdeto (http://www.irdeto.com)
 */
class JumpstartSeed extends AbstractRecipeSeed
{

    public $genres = array("Action",
        "Adventure",
        "Animation",
        "Biography",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Family",
        "Fantasy",
        "Film-Noir",
        "History",
        "Horror",
        "Music",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Sport",
        "Thriller",
        "War",
        "Western");

    public $movies = array(
        'The Shawshank Redemption',
        'The Godfather',
        'The Godfather: Part II',
        'Pulp Fiction',
        'The Good, the Bad and the Ugly',
        'The Dark Knight',
        '12 Angry Men',
        'Schindler\'s List',
        'The Lord of the Rings: The Return of the King',
        'Fight Club',
        'Star Wars: Episode V - The Empire Strikes Back',
        'The Lord of the Rings: The Fellowship of the Ring',
        'One Flew Over the Cuckoo\'s Nest',
        'Goodfellas',
        'Seven Samurai',
        'Inception',
        'Star Wars',
        'Forrest Gump',
        'The Matrix',
        'The Lord of the Rings: The Two Towers',
        'City of God',
        'The Silence of the Lambs',
        'Se7en',
        'Once Upon a Time in the West',
        'Casablanca',
        'The Usual Suspects',
        'Raiders of the Lost Ark',
        'Rear Window',
        'It\'s a Wonderful Life',
        'Psycho',
        'Léon: The Professional',
        'Sunset Blvd.',
        'American History X',
        'Apocalypse Now',
        'Terminator 2: Judgment Day',
        'Memento',
        'Saving Private Ryan',
        'City Lights',
        'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
        'Alien',
        'Modern Times',
        'Spirited Away',
        'Gravity',
        'North by Northwest',
        'Back to the Future',
        'Citizen Kane',
        'The Pianist',
        'M',
        'Life Is Beautiful',
        'The Shining',
        'The Departed',
        'Paths of Glory',
        'Vertigo',
        'American Beauty',
        'Django Unchained',
        'Double Indemnity',
        'The Dark Knight Rises',
        'Taxi Driver',
        'Aliens',
        'The Green Mile',
        'The Intouchables',
        'Gladiator',
        'WALL·E',
        'The Lives of Others',
        'Toy Story 3',
        'The Great Dictator',
        'A Clockwork Orange',
        'The Prestige',
        'Amélie',
        'Lawrence of Arabia',
        'To Kill a Mockingbird',
        'Reservoir Dogs',
        'Das Boot',
        'Cinema Paradiso',
        'The Lion King',
        'The Treasure of the Sierra Madre',
        'The Third Man',
        'Once Upon a Time in America',
        'Requiem for a Dream',
        'Star Wars: Episode VI - Return of the Jedi',
        'Eternal Sunshine of the Spotless Mind',
        'Full Metal Jacket',
        'Braveheart',
        'L.A. Confidential',
        'Oldboy',
        'Singin\' in the Rain',
        'Metropolis',
        'Chinatown',
        'Rashomon',
        'Some Like It Hot',
        'Bicycle Thieves',
        'All About Eve',
        'Monty Python and the Holy Grail',
        'Princess Mononoke',
        'Amadeus',
        '2001: A Space Odyssey',
        'Witness for the Prosecution',
        'The Apartment',
        'The Sting',
        'Unforgiven',
        'Grave of the Fireflies',
        'Indiana Jones and the Last Crusade',
        'Raging Bull',
        'The Bridge on the River Kwai',
        'Die Hard',
        'Yojimbo',
        'Batman Begins',
        'A Separation',
        'Inglourious Basterds',
        'For a Few Dollars More',
        'Mr. Smith Goes to Washington',
        'Snatch.',
        'Toy Story',
        'On the Waterfront',
        'The Great Escape',
        'Downfall',
        'Pan\'s Labyrinth',
        'Up',
        'The General',
        'The Seventh Seal',
        'Heat',
        'The Elephant Man',
        'The Maltese Falcon',
        'The Kid',
        'Blade Runner',
        'Wild Strawberries',
        'Rebecca',
        'Scarface',
        'Ikiru',
        'Ran',
        'Fargo',
        'Gran Torino',
        'Touch of Evil',
        'The Big Lebowski',
        'The Gold Rush',
        'The Deer Hunter',
        'Cool Hand Luke',
        'It Happened One Night',
        'Diabolique',
        'No Country for Old Men',
        'The Sixth Sense',
        'Lock, Stock and Two Smoking Barrels',
        'Jaws',
        'Good Will Hunting',
        'Strangers on a Train',
        'Casino',
        'Judgment at Nuremberg',
        'The Grapes of Wrath',
        'The Wizard of Oz',
        'Platoon',
        'Sin City',
        'Butch Cassidy and the Sundance Kid',
        'Kill Bill: Vol. 1',
        'The Thing',
        'Trainspotting',
        'Gone with the Wind',
        'High Noon',
        'Annie Hall',
        'Hotel Rwanda',
        'The Hunt',
        'Warrior',
        'The Secret in Their Eyes',
        'Finding Nemo',
        'My Neighbor Totoro',
        'V for Vendetta',
        'Notorious',
        'Dial M for Murder',
        'The Avengers',
        'How to Train Your Dragon',
        'Life of Brian',
        'Into the Wild',
        'The Best Years of Our Lives',
        'Network',
        'The Terminator',
        'Million Dollar Baby',
        'There Will Be Blood',
        'Ben-Hur',
        'The Night of the Hunter',
        'The Big Sleep',
        'The King\'s Speech',
        'Stand by Me',
        'The 400 Blows',
        'Twelve Monkeys',
        'Groundhog Day',
        'Donnie Darko',
        'Dog Day Afternoon',
        'Amores Perros',
        'Howl\'s Moving Castle',
        'Mary and Max',
        'Gandhi',
        'The Bourne Ultimatum',
        'A Beautiful Mind',
        'Persona',
        'The Killing',
        'The Graduate',
        'Rush',
        'Black Swan',
        'The Princess Bride',
        'Who\'s Afraid of Virginia Woolf?',
        'The Hustler',
        'The Man Who Shot Liberty Valance',
        'La Strada',
        'Anatomy of a Murder',
        '8½',
        'The Manchurian Candidate',
        'Rocky',
        'The Exorcist',
        'Slumdog Millionaire',
        'In the Name of the Father',
        'Stalag 17',
        'Rope',
        'The Wild Bunch',
        'Barry Lyndon',
        'Fanny and Alexander',
        'Monsters, Inc.',
        'Infernal Affairs',
        'The Truman Show',
        'Roman Holiday',
        'Life of Pi',
        'Pirates of the Caribbean: The Curse of the Black Pearl',
        'Memories of Murder',
        'Sleuth',
        'All Quiet on the Western Front',
        'Harry Potter and the Deathly Hallows: Part 2',
        'Stalker',
        'Jurassic Park',
        'A Streetcar Named Desire',
        'Star Trek',
        'Ratatouille',
        'Ip Man',
        'A Fistful of Dollars',
        'The Diving Bell and the Butterfly',
        'The Hobbit: An Unexpected Journey',
        'District 9',
        'Shutter Island',
        'Rain Man',
        'Incendies',
        'Rosemary\'s Baby',
        '3 Idiots',
        'La Haine',
        'The Artist',
        'Nausicaä of the Valley of the Wind',
        'Beauty and the Beast',
        'Three Colors: Red',
        'Bringing Up Baby',
        'Mystic River',
        'Arsenic and Old Lace',
        'In the Heat of the Night',
        'Papillon',
        'Before Sunrise'
            );

    public $actors = array('Jack Nicholson',
        'Ralph Fiennes',
        'Daniel Day-Lewis',
        'Robert De Niro',
        'Al Pacino',
        'Dustin Hoffman',
        'Tom Hanks',
        'Brad Pitt',
        'Anthony Hopkins',
        'Marlon Brando',
        'Jeremy Irons',
        'Denzel Washington',
        'Gene Hackman',
        'Jeff Bridges',
        'Tim Robbins');

    public $brands = array("Breaking Bad",
        "Planet Earth",
        "Game of Thrones",
        "he Wire",
        "Sherlock",
        "Cosmos",
        "The Sopranos",
        "Arrested Development",
        "Firefly",
        "Life",
        "Dexter",
        "Avatar: The Last Airbender",
        "The Simpsons",
        "Monty Python's Flying Circus",
        "Freaks and Geeks",
        "The Twilight Zone",
        "Twin Peaks",
        "Rome",
        "Desu nôto",
        "Seinfeld",
        "Oz",
        "House M.D.",
        "House of Cards",
        "Friends",
        "Leyla ile Mecnun",
        "Batman: The Animated Series",
        "Deadwood",
        "Fawlty Towers",
        "South Park",
        "Kaubôi bibappu: Cowboy Bebop",
        "Blackadder Goes Forth",
        "Suits",
        "It's Always Sunny in Philadelphia",
        "Six Feet Under",
        "Archer",
        "Top Gear",
        "Black-Adder II",
        "Doctor Who",
        "The Daily Show",
        "Downton Abbey",
        "The Office",
        "Dragon Ball Z",
        "Battlestar Galactica",
        "Black Adder the Third",
        "The X Files",
        "The Walking Dead",
        "Boardwalk Empire",
        "Curb Your Enthusiasm",
        "Spaced",
        "The Shield"
        );

    protected function createSeed()
    {
        $locale = 'en_US';

        foreach ($this->genres as $k => $genre) {
            $genresArray[$k] = $this->create('genre');
            $genresArray[$k]->set('logicalKey', $genre);
            $genresArray[$k]->set('title', $genre);
        }

        foreach ($this->movies as $k => $movie) {

            $actorId = rand(0,count($this->actors)-1);
            $actor = $this->create('person');
            $actor->set('firstName', substr($this->actors[$actorId].' : '.$locale, 0 ,15), $locale);
            $actor->set('lastName', substr($this->actors[$actorId].' : '.$locale,0 ,15), $locale);
            $actor->set('fullName', $this->actors[$actorId].' : '.$locale, $locale);

            $program = $this->create('program');
            $program->set('titleLong', $movie.' : '.$locale, $locale);
            $program->set('uriId',$k.'_'.rand(1000,9999).'__'.$movie);
            $program->addRelationship('actors', $actor);
            $program->addRelationship('genres', $genresArray[rand(0, count($genre)-1)]);
        }

        foreach ($this->brands as $brand_name) {

            $brand = $this->create('brand');
            $brand->set('uriId', $brand_name.':'.$locale);
            $brand->set('titleLong', $brand_name);

            for ($i=0;$i<2;$i++) {
                $poster_name = 'poster'.$i.'_4_brand_'.$brand_name;

                $poster = $this->create('poster');
                $poster->set('uriId', $poster_name);

                $poster_subcontent = $this->create('posterSubcontent');
                $poster_subcontent->set('xResolution', rand(1,100));
                $poster_subcontent->set('yResolution', rand(1,100));
                $poster_subcontent->set('filename', $poster_name.' sc');

                $poster->addRelationship('subcontent', $poster_subcontent);

                $brand->addRelationship('posters', $poster);
            }
        }
    }
}